// Generated by https://quicktype.io
//
// To change quicktype's target language, run command:
//
//   "Set quicktype target language"

export interface DynamicFeedJson {
  code: number
  message: string
  ttl: number
  data: Data
}

export interface Data {
  has_more: boolean
  items: DynamicFeedItem[]
  offset: string
  update_baseline: string
  update_num: number
}

export interface DynamicFeedItem {
  basic: Basic
  id_str: string
  modules: DynamicFeedItemModules
  type: string
  visible: boolean
  orig?: Orig
}

export interface Basic {
  comment_id_str: string
  comment_type: number
  like_icon: LikeIcon
  rid_str: string
  jump_url?: string
}

export interface LikeIcon {
  action_url: string
  end_url: string
  id: number
  start_url: string
}

export interface DynamicFeedItemModules {
  module_author: PurpleModuleAuthor
  module_dynamic: PurpleModuleDynamic
  module_more: ModuleMore
  module_stat: ModuleStat
}

export interface PurpleModuleAuthor {
  avatar?: PurpleAvatar
  decorate?: Decorate
  face: string
  face_nft: boolean
  following: boolean
  jump_url: string
  label: string
  mid: number
  name: string
  official_verify?: OfficialVerify
  pendant?: Pendant
  pub_action: string
  pub_location_text?: string
  pub_time: string
  pub_ts: number
  type: string
  vip?: Vip
}

export interface PurpleAvatar {
  container_size: ContainerSize
  fallback_layers: PurpleFallbackLayers
  mid: string
}

export interface ContainerSize {
  height: number
  width: number
}

export interface PurpleFallbackLayers {
  is_critical_group: boolean
  layers: PurpleLayer[]
}

export interface PurpleLayer {
  general_spec: GeneralSpec
  layer_config: PurpleLayerConfig
  resource: Resource
  visible: boolean
}

export interface GeneralSpec {
  pos_spec: PosSpec
  render_spec: RenderSpec
  size_spec: ContainerSize
}

export interface PosSpec {
  axis_x: number
  axis_y: number
  coordinate_pos: number
}

export interface RenderSpec {
  opacity: number
}

export interface PurpleLayerConfig {
  is_critical?: boolean
  tags: PurpleTags
}

export interface PurpleTags {
  AVATAR_LAYER?: AvatarLayer
  GENERAL_CFG?: PurpleGENERALCFG
  ICON_LAYER?: AvatarLayer
  PENDENT_LAYER?: AvatarLayer
}

export interface AvatarLayer {}

export interface PurpleGENERALCFG {
  config_type: number
  general_config: PurpleGeneralConfig
}

export interface PurpleGeneralConfig {
  web_css_style: PurpleWebCSSStyle
}

export interface PurpleWebCSSStyle {
  'borderRadius': string
  'background-color'?: string
  'border'?: string
  'boxSizing'?: string
}

export interface Resource {
  res_image: ResImage
  res_type: number
}

export interface ResImage {
  image_src: ImageSrc
}

export interface ImageSrc {
  placeholder?: number
  remote?: Remote
  src_type: number
  local?: number
}

export interface Remote {
  bfs_style: string
  url: string
}

export interface Decorate {
  card_url: string
  fan: Fan
  id: number
  jump_url: string
  name: string
  type: number
}

export interface Fan {
  color: string
  color_format: ColorFormat | null
  is_fan: boolean
  num_prefix: string
  num_str: string
  number: number
}

export interface ColorFormat {
  colors: string[]
  end_point: string
  gradients: number[]
  start_point: string
}

export interface OfficialVerify {
  desc: string
  type: number
}

export interface Pendant {
  expire: number
  image: string
  image_enhance: string
  image_enhance_frame: string
  n_pid: number
  name: string
  pid: number
}

export interface Vip {
  avatar_subscript: number
  avatar_subscript_url: string
  due_date: number
  label: LabelClass
  nickname_color: string
  status: number
  theme_type: number
  type: number
}

export interface LabelClass {
  bg_color: string
  bg_style: number
  border_color: string
  img_label_uri_hans: string
  img_label_uri_hans_static: string
  img_label_uri_hant: string
  img_label_uri_hant_static: string
  label_theme: string
  path: string
  text: string
  text_color: string
  use_img_label: boolean
}

export interface PurpleModuleDynamic {
  additional: null
  desc: Desc | null
  major: PurpleMajor | null
  topic: Topic | null
}

export interface Desc {
  rich_text_nodes: Rich[]
  text: string
}

export interface Rich {
  orig_text: string
  text: string
  type: RichTextNodeType
  jump_url?: string
}

export enum RichTextNodeType {
  RichTextNodeTypeText = 'RICH_TEXT_NODE_TYPE_TEXT',
  RichTextNodeTypeTopic = 'RICH_TEXT_NODE_TYPE_TOPIC',
}

export interface PurpleMajor {
  archive?: Archive
  type: string
  opus?: Opus
  pgc?: Pgc
  ugc_season?: UgcSeason
  live_rcmd?: LiveRcmd
}

export interface Archive {
  aid: string
  badge: Badge
  bvid: string
  cover: string
  desc: string
  disable_preview: number
  duration_text: string
  jump_url: string
  stat: Stat
  title: string
  type: number
}

export interface Badge {
  bg_color: string
  color: string
  icon_url?: null
  text: string
}

export interface Stat {
  danmaku: string
  play: string
}

export interface LiveRcmd {
  content: string
  reserve_type: number
}

export interface Opus {
  fold_action: string[]
  jump_url: string
  pics: Pic[]
  summary: Summary
  title: null | string
}

export interface Pic {
  aigc: null
  height: number
  live_url: null
  size: number
  url: string
  width: number
}

export interface Summary {
  rich_text_nodes: Rich[]
  text: string
  has_more?: boolean
  paragraphs?: Paragraph[]
}

export interface Paragraph {
  align: number
  format: Format
  para_type: number
  text: Text
}

export interface Format {
  align: number
  indent: null
}

export interface Text {
  nodes: Node[]
}

export interface Node {
  type: string
  word?: Word
  rich?: Rich
}

export interface Word {
  bg_style: BgStyle
  color: null
  font_level: string
  style: AvatarLayer
  words: string
}

export interface BgStyle {
  color: AvatarLayer
}

export interface Pgc {
  badge: Badge
  cover: string
  epid: number
  jump_url: string
  season_id: number
  stat: Stat
  sub_type: number
  title: string
  type: number
}

export interface UgcSeason {
  aid: number
  badge: Badge
  bvid: string
  cover: string
  desc: string
  disable_preview: number
  duration_text: string
  jump_url: string
  stat: Stat
  title: string
  type: number
}

export interface Topic {
  id: number
  jump_url: string
  name: string
}

export interface ModuleMore {
  three_point_items: ThreePointItem[]
}

export interface ThreePointItem {
  label: LabelEnum
  type: ThreePointItemType
}

export enum LabelEnum {
  举报 = '举报',
  取消关注 = '取消关注',
}

export enum ThreePointItemType {
  ThreePointFollowing = 'THREE_POINT_FOLLOWING',
  ThreePointReport = 'THREE_POINT_REPORT',
}

export interface ModuleStat {
  comment: Comment
  forward: Forward
  like: Like
}

export interface Comment {
  count: number
  forbidden: boolean
  hidden?: boolean
}

export interface Forward {
  count: number
  forbidden: boolean
}

export interface Like {
  count: number
  forbidden: boolean
  status: boolean
}

export interface Orig {
  basic: Basic
  id_str: string
  modules: OrigModules
  type: string
  visible: boolean
}

export interface OrigModules {
  module_author: FluffyModuleAuthor
  module_dynamic: FluffyModuleDynamic
}

export interface FluffyModuleAuthor {
  avatar: FluffyAvatar
  face: string
  face_nft: boolean
  following: boolean
  jump_url: string
  label: string
  mid: number
  name: string
  official_verify: OfficialVerify
  pendant: Pendant
  pub_action: string
  pub_time: string
  pub_ts: number
  type: string
  vip: Vip
}

export interface FluffyAvatar {
  container_size: ContainerSize
  fallback_layers: FluffyFallbackLayers
  mid: string
}

export interface FluffyFallbackLayers {
  is_critical_group: boolean
  layers: FluffyLayer[]
}

export interface FluffyLayer {
  general_spec: GeneralSpec
  layer_config: FluffyLayerConfig
  resource: Resource
  visible: boolean
}

export interface FluffyLayerConfig {
  is_critical: boolean
  tags: FluffyTags
}

export interface FluffyTags {
  AVATAR_LAYER: AvatarLayer
  GENERAL_CFG: FluffyGENERALCFG
}

export interface FluffyGENERALCFG {
  config_type: number
  general_config: FluffyGeneralConfig
}

export interface FluffyGeneralConfig {
  web_css_style: FluffyWebCSSStyle
}

export interface FluffyWebCSSStyle {
  borderRadius: string
}

export interface FluffyModuleDynamic {
  additional: null
  desc: Desc
  major: FluffyMajor
  topic: null
}

export interface FluffyMajor {
  archive: Archive
  type: string
}
